do not name unused parameter
to resolve -Werror with clang:

> ompl/src/ompl/base/spaces/src/TrochoidStateSpace.cpp:586:117: error: unused parameter 'wind_ratio' [-Werror,-Wunused-parameter]
>   586 |     bool isLongPathCase(double x0, double y0, double phi0, double xf, double yf, double phif, double radius, double wind_ratio)